

# Build settings
plugins:
  - jekyll-seo-tag




# Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

#footer: 'follow us on <a href="https://twitter.com/CyberSecurityLI">twitter</a>, <a href="https://www.instagram.com/cybersecurityli">instagram</a> or <a href="https://www.facebook.com/cybersec.liechtenstein">facebook</a>'
